apiVersion: terraria.terraria-operator/v1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: terraria-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: terraria-operator
  name: server-sample
spec:
  # TODO(user): Add fields here
